services:
  registry:
    container_name: registry
    build:
      context: ..\..\..\services\tools.descartes.teastore.registry
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      OTEL_SERVICE_NAME: registry
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_INSTRUMENTATION_JDBC_ENABLED: true
      OTEL_INSTRUMENTATION_JPA_ENABLED: true
      OTEL_LOG_LEVEL: info
    depends_on:
      - jaeger

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"

  persistence:
    container_name: persistence
    build:
      context: ..\..\..\services\tools.descartes.teastore.persistence
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
      OTEL_SERVICE_NAME: persistence
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_INSTRUMENTATION_JDBC_ENABLED: true
      OTEL_INSTRUMENTATION_JPA_ENABLED: true
      OTEL_LOG_LEVEL: info
    depends_on:
      - jaeger

  auth:
    container_name: auth
    build:
      context: ..\..\..\services\tools.descartes.teastore.auth
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
      OTEL_SERVICE_NAME: auth
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_INSTRUMENTATION_JDBC_ENABLED: true
      OTEL_INSTRUMENTATION_JPA_ENABLED: true
      OTEL_LOG_LEVEL: info
    depends_on:
      - jaeger

  image:
    container_name: image
    build:
      context: ..\..\..\services\tools.descartes.teastore.image
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
      OTEL_SERVICE_NAME: image
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_INSTRUMENTATION_JDBC_ENABLED: true
      OTEL_INSTRUMENTATION_JPA_ENABLED: true
      OTEL_LOG_LEVEL: info
    depends_on:
      - jaeger

  recommender:
    container_name: recommender
    build:
      context: ..\..\..\services\tools.descartes.teastore.recommender
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
      OTEL_SERVICE_NAME: recommender
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_INSTRUMENTATION_JDBC_ENABLED: true
      OTEL_INSTRUMENTATION_JPA_ENABLED: true
      OTEL_LOG_LEVEL: info
    depends_on:
      - jaeger

  webui:
    container_name: webui
    build:
      context: ..\..\..\services\tools.descartes.teastore.webui
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
      OTEL_SERVICE_NAME: webui
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_INSTRUMENTATION_JDBC_ENABLED: true
      OTEL_INSTRUMENTATION_JPA_ENABLED: true
      OTEL_LOG_LEVEL: info
    ports:
      - "8080:8080"
    depends_on:
      - jaeger

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250" # to send spans in Protobuf format via grpc (jaeger specific)
      - "16686:16686" # jaeger ui
      - "16685:16685" # grpc query service
    environment:
      - COLLECTOR_OTLP_ENABLED=true
